# Generated by Django 2.1.4 on 2019-01-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('video', models.FileField(null=True, upload_to='video/')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='image_gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workout_portal.ExerciseImage'),
        ),
        migrations.AddField(
            model_name='training',
            name='video_gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='workout_portal.ExerciseVideo'),
        ),
    ]
