# Generated by Django 2.1.4 on 2019-01-06 14:30

from django.db import migrations
from django.contrib.auth.hashers import make_password
from datetime import datetime
from random import randrange


def generate_workoutset(apps, exercise):
    WorkoutSet = apps.get_model("workout_portal", "WorkoutSet")
    for i in range(0, randrange(5)):
        workoutset = WorkoutSet(
            weight=i,
            repetitions=randrange(0, 100, 2),
            duration=randrange(0, 100),
            additional='additional information {}'.format(i),
            exercise=exercise
        )
        workoutset.save()


def generate_exercise(apps, training):
    Exercise = apps.get_model("workout_portal", "Exercise")
    for i in range(0, randrange(5)):
        exercise = Exercise(
            name='exercise_{}'.format(i),
            description='desc_{}'.format(i),
            training=training
        )
        exercise.save()


def generate_trainings(apps, user):
    Training = apps.get_model("workout_portal", "Training")
    for i in range(0, 10):
        training = Training(
            name="training_{}".format(i),
            date=datetime(year=2018, month=i + 1, day=i + 2),
            user=user
        )
        training.save()
        generate_exercise(apps, training)


def generate_data(apps, schema_editor):
    User = apps.get_registered_model('auth', 'User')
    user = User(
        username='test_{}'.format(randrange(50000)),
        email='test@test.com',
        password=make_password('test'),
        is_superuser=True,
        is_staff=True
    )
    user.save()
    generate_trainings(apps, user)


class Migration(migrations.Migration):

    dependencies = [
        ('workout_portal', '0003_model_changes'),
    ]

    operations = [
        migrations.RunPython(generate_data),
    ]
